import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Hero, Features } from '@/components/sections';
import { Layout } from '@/components/layout';
import { ArrowRight } from 'lucide-react';
import { useAuth } from '@/app/providers/auth-provider';
import CloudIllustration from '@/components/auth/CloudIllustration';
import LoginCard from '@/components/auth/LoginCard';
/**
 * Home Page
 * Landing page with hero section and feature overview
 * Shows login page if not authenticated
 */
export default function HomePage() {
    const { isAuthenticated } = useAuth();
    // If not authenticated, show login page
    if (!isAuthenticated) {
        return (_jsx("div", { className: "min-h-screen w-full bg-gradient-to-br from-[#06070f] to-[#0b1020] text-white", children: _jsx("div", { className: "max-w-full mx-auto min-h-screen", children: _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-12 min-h-screen", children: [_jsxs("div", { className: "lg:col-span-7 relative flex items-center justify-center p-8 order-2 lg:order-1", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-tr from-[#061025] via-[#0b1a2b] to-transparent opacity-60" }), _jsxs("div", { className: "relative z-10 max-w-4xl w-full", children: [_jsxs("div", { className: "mb-6", children: [_jsxs(motion.h1, { className: "text-3xl md:text-4xl lg:text-5xl font-extrabold leading-tight", initial: { opacity: 0, x: -20 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.6 }, children: ["Deploy to AWS without", _jsx("br", {}), " DevOps complexity."] }), _jsx(motion.p, { className: "mt-4 text-white/70 max-w-xl", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.2 }, children: "CloudOps automates builds, deployments, and monitoring so your team can focus on product." })] }), _jsx("div", { className: "mt-8", children: _jsx(CloudIllustration, {}) }), _jsx(motion.div, { animate: { y: [0, -8, 0] }, transition: { duration: 6, repeat: Infinity }, className: "absolute right-8 top-12 hidden md:block", children: _jsx("div", { className: "p-3 rounded-full bg-gradient-to-tr from-primary to-accent shadow-lg", children: " " }) })] })] }), _jsx("div", { className: "lg:col-span-5 flex items-center justify-center p-8 order-1 lg:order-2", children: _jsx("div", { className: "w-full max-w-lg", children: _jsxs(motion.div, { initial: { opacity: 0, scale: 0.98 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 0.6 }, children: [_jsxs("div", { className: "mb-6 text-center", children: [_jsx("div", { className: "text-sm text-white/60", children: "Welcome to" }), _jsx("div", { className: "text-2xl font-bold", children: "CloudOps" }), _jsx("div", { className: "text-sm text-white/60", children: "Secure DevOps automation for teams" })] }), _jsx(LoginCard, {}), _jsx("div", { className: "mt-6 text-center text-xs text-white/50", children: "By signing in you agree to our Terms and that you have read our Privacy Policy." })] }) }) })] }) }) }));
    }
    // If authenticated, show the dashboard/home content
    return (_jsxs(Layout, { showNavbar: true, children: [_jsx(Hero, {}), _jsx(Features, {}), _jsx("section", { className: "py-20 md:py-32 px-4 md:px-8", children: _jsx("div", { className: "max-w-4xl mx-auto", children: _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, viewport: { once: true }, className: "relative backdrop-blur-md bg-gradient-to-r from-primary/20 to-accent/20 border border-primary/50 rounded-2xl p-8 md:p-16 text-center overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 rounded-2xl border border-transparent bg-gradient-to-r from-primary/10 via-accent/5 to-primary/10 pointer-events-none animate-gradient-rotate" }), _jsxs("div", { className: "relative z-10", children: [_jsx("h3", { className: "text-2xl md:text-4xl font-bold text-text-primary mb-4", children: "Ready to Deploy Faster?" }), _jsx("p", { className: "text-lg text-text-secondary mb-8 max-w-2xl mx-auto", children: "Join hundreds of developers and start deploying to AWS in minutes, not hours." }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4 justify-center", children: [_jsxs(motion.button, { whileHover: { scale: 1.05 }, whileTap: { scale: 0.98 }, className: "px-8 py-4 bg-gradient-to-r from-primary to-primary/80 text-white rounded-lg font-semibold flex items-center justify-center gap-2 hover:shadow-lg transition-all duration-300", children: ["Get Started Free", _jsx(ArrowRight, { className: "w-5 h-5" })] }), _jsx(motion.button, { whileHover: { scale: 1.05 }, whileTap: { scale: 0.98 }, className: "px-8 py-4 bg-surface-glass/50 backdrop-blur-md border-2 border-border hover:border-accent text-text-primary rounded-lg font-semibold transition-all duration-300", children: "Schedule Demo" })] }), _jsx("p", { className: "text-sm text-text-secondary mt-6", children: "No credit card required. Free tier includes unlimited deployments." })] })] }) }) }), _jsx("section", { className: "py-16 md:py-24 px-4 md:px-8 border-t border-border/30", children: _jsx("div", { className: "max-w-7xl mx-auto", children: _jsx("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-8 text-center", children: [
                            { number: '5000+', label: 'Deployments Monthly' },
                            { number: '99.9%', label: 'Platform Uptime' },
                            { number: '500+', label: 'Active Users' },
                            { number: '< 2min', label: 'Deploy Time' },
                        ].map((stat, index) => (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.6, delay: index * 0.1 }, viewport: { once: true }, children: [_jsx("div", { className: "text-3xl md:text-4xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent", children: stat.number }), _jsx("p", { className: "text-text-secondary mt-2", children: stat.label })] }, stat.label))) }) }) })] }));
}
