import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Github } from 'lucide-react';
import { useAuth } from '@/app/providers/auth-provider';
const LoginCard = () => {
    const { isAuthenticated, user } = useAuth();
    const userName = user?.username || user?.name || user?.login || user?.email || 'GitHub User';
    return (_jsxs(motion.div, { className: "w-full max-w-md mx-auto p-8 rounded-2xl relative bg-[rgba(19,26,42,0.6)] backdrop-blur-md border border-white/10 shadow-xl", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, children: [_jsx("div", { className: "absolute -inset-0.5 bg-gradient-to-r from-primary to-accent rounded-2xl blur opacity-30 -z-10" }), _jsxs("div", { className: "flex flex-col gap-4 z-10", children: [_jsx("h3", { className: "text-2xl font-bold text-white", children: "Welcome back" }), _jsx("p", { className: "text-sm text-white/70", children: "Sign in to manage your deployments and monitoring." }), isAuthenticated ? (_jsxs("div", { className: "mt-4 rounded-lg border border-white/10 bg-white/5 p-4 text-white", children: [_jsx("div", { className: "text-xs text-white/60", children: "Signed in as" }), _jsx("div", { className: "mt-2 text-lg font-semibold", children: userName })] })) : (_jsxs("button", { className: "mt-4 flex items-center justify-center gap-3 w-full py-3 rounded-lg bg-gradient-to-r from-[#0f1724]/60 to-[#0b1220]/40 border border-white/10 hover:from-[#0b1220]/80 transition-all duration-200", onClick: () => window.location.assign('http://localhost:5000/auth/github'), "aria-label": "Sign in with GitHub", children: [_jsx(Github, { className: "w-5 h-5 text-white" }), _jsx("span", { className: "text-sm font-semibold text-white", children: "Continue with GitHub" })] })), _jsx("div", { className: "pt-2", children: _jsxs("div", { className: "text-xs text-white/60", children: [_jsx("strong", { className: "text-white", children: "Security:" }), " We use GitHub OAuth and store tokens securely. ", _jsx("br", {}), "Your data is encrypted in transit and at rest."] }) }), _jsxs("div", { className: "pt-2 flex items-center gap-2 text-xs text-white/50", children: [_jsx("input", { id: "remember", type: "checkbox", className: "w-4 h-4 rounded bg-white/5" }), _jsx("label", { htmlFor: "remember", children: "Remember me on this device" })] }), _jsxs("div", { className: "mt-2 text-center text-xs text-white/40", children: ["By continuing you agree to our ", _jsx("a", { href: "#", className: "text-accent underline", children: "Privacy Policy" }), "."] })] })] }));
};
export default LoginCard;
